name: Laravel

on:
  pull_request:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer, cs2pr
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          list-files: shell
          filters: |
            php:
              - added|modified: '**/*.php'
      - name: Run phpcs
        id: phpcs
        if: ${{ steps.changes.outputs.php == 'true' }}
        run: composer cs-report ${{steps.changes.outputs.php_files}}
      - name: Show PHPCS results in PR
        if: ${{ always() && steps.changes.outputs.php == 'true' && steps.phpcs.outcome == 'failure' }}
        run: cs2pr ./phpcs-report.xml
